### ISSUE TITLE
Public repo not propagating access in all cases

### ISSUE THREAD

**Issue by dcramer** [getsentry/zeus#109]
https://sentry.io/sentry/zeus/issues/417370823/

```
Error: Repository not found or you do not have access
  at ExtendableBuiltin (/usr/src/zeus/js/app.a34ab85d.js:863:608)
  at new t (/usr/src/zeus/js/app.a34ab85d.js:863:2873)
  at getDefaultState (/usr/src/zeus/webapp/pages/RepositoryDetails.jsx:36:13)
  at AsyncPage (/usr/src/zeus/webapp/components/AsyncPage.jsx:21:23)
  at new t (/usr/src/zeus/js/app.a34ab85d.js:18120:3060)
...
(18 additional frame(s) were not displayed)
```

**Comment by dcramer** [comment]
@keegancsmith ^ this is the issue you hit

You should be able to view Zeus, but I'm guessing the tenant stuff isn't behaving correctly in a specific case

**Comment by dcramer** [comment]
Oh the issue is because we fetch the repo details from the 'list of repos i have access to', but that list intentionally doesnt contain public repos because its an unbounded length. I'll just change the code to hit the server when the repos not available in the cache.
