### ISSUE TITLE
Zeus main page raising 500

### ISSUE THREAD

**Issue by amureki** [getsentry/zeus#45]
Hi peeps!

I tried to access https://zeus.ci/login?next=%2Fbuilds but got 500:
```
The exception Zeus reported was:

TypeError: Cannot read property 'map' of undefined
    at Function.t.a.Object.loadBuildsForUser [as mapToProps] (https://zeus.ci/static/bundle.js:1:1209521)
    at r (https://zeus.ci/static/bundle.js:1:226744)
    at Function.r.mapToProps (https://zeus.ci/static/bundle.js:1:226863)
    at r (https://zeus.ci/static/bundle.js:1:226726)
    at o (https://zeus.ci/static/bundle.js:1:509021)
    at https://zeus.ci/static/bundle.js:1:509519
    at Object.run (https://zeus.ci/static/bundle.js:1:220513)
    at u.initSelector (https://zeus.ci/static/bundle.js:1:223050)
    at new u (https://zeus.ci/static/bundle.js:1:221953)
    at constructClassInstance (https://zeus.ci/static/bundle.js:1:407946)
    at beginWork (https://zeus.ci/static/bundle.js:1:411500)
    at o (https://zeus.ci/static/bundle.js:1:423836)
    at c (https://zeus.ci/static/bundle.js:1:424352)
    at u (https://zeus.ci/static/bundle.js:1:424827)
    at g (https://zeus.ci/static/bundle.js:1:426849)
    at m (https://zeus.ci/static/bundle.js:1:426358)
    at Object.enqueueSetState (https://zeus.ci/static/bundle.js:1:407628)
    at u.a.setState (https://zeus.ci/static/bundle.js:1:364262)
    at u.onStateChange (https://zeus.ci/static/bundle.js:1:223491)
    at Object.notify (https://zeus.ci/static/bundle.js:1:500277)
    at e.notifyNestedSubs (https://zeus.ci/static/bundle.js:1:500780)
    at u.onStateChange (https://zeus.ci/static/bundle.js:1:223509)
    at u (https://zeus.ci/static/bundle.js:1:225193)
    at https://zeus.ci/static/bundle.js:1:1218171
    at https://zeus.ci/static/bundle.js:1:1211829
    at dispatch (https://zeus.ci/static/bundle.js:1:507722)
    at https://zeus.ci/static/bundle.js:1:227986
    at <anonymous>
```

**Comment by dcramer** [comment]
I think this is just us not handling the race between data population for unauthed users.

Should be fixed in 0ed66e6c955bc3f26f40e8478e0ae065de8bb14e (which I'm deploying now)
